# Generated by Django 3.0.4 on 2020-06-13 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0003_auto_20200606_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='likes',
        ),
        migrations.AddField(
            model_name='chapter',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
