# Generated by Django 3.0.4 on 2020-06-13 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_auto_20200612_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='story_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='bookmarks'),
        ),
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(default='noimage.png', upload_to='user_uploads/covers'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='chapter_likes', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
