# Generated by Django 3.2 on 2021-12-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
