# Generated by Django 3.2 on 2021-12-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
